#!/usr/bin/env python3
"""Bake Instinct 296x128 RGBA goldens into zlib blobs for slab_ui_render."""

from __future__ import annotations

import zlib
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "design" / "instinct-firmware-goldens-pr1"
OUT = ROOT / "firmware" / "src" / "slab_frames.c"
OUT_1BIT = ROOT / "firmware" / "src" / "slab_frames_1bit.c"

INK_LUMA = 140

FRAMES = [
    ("DEFAULT_HOLE", "01-default-hole.png"),
    ("STROKE_EDIT", "02-stroke-edit.png"),
    ("PUTTS_INPUT", "03-putts-input.png"),
    ("END_HOLE_CONFIRM", "04-end-hole-confirm.png"),
    ("ROUND_COMPLETE_SYNC", "05-round-complete-sync.png"),
    ("DERIVED_STATS", "06-derived-stats.png"),
]


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02X}")
        if len(chunk) == 16:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def pack_1bit(im: Image.Image) -> bytes:
    """MSB-first packed 1-bit, ink=1 when luma < INK_LUMA. Matches host slab_ui_render."""
    rgba = im.convert("RGBA")
    out = bytearray(37 * 128)
    px = rgba.load()
    for y in range(128):
        for x in range(296):
            r, g, b, _a = px[x, y]
            luma = (r * 30 + g * 59 + b * 11) // 100
            if luma < INK_LUMA:
                out[y * 37 + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def main() -> None:
    blobs = []
    arrays = []
    for key, filename in FRAMES:
        path = SRC / filename
        im = Image.open(path).convert("RGBA")
        if im.size != (296, 128):
            raise SystemExit(f"{path} is {im.size}, expected 296x128")
        z = zlib.compress(im.tobytes(), 9)
        arr = f"kZ{key}"
        arrays.append(c_array(arr, z))
        blobs.append(f"    {{ {arr}, {len(z)} }}, /* {filename} */")

    text = f"""/* SPDX-License-Identifier: MIT */
/* Instinct locked 296x128 RGBA frames (zlib). Regenerated by
 * firmware/tools/bake_instinct_frames.py from
 * design/instinct-firmware-goldens-pr1/. Do not hand-edit.
 * Host/emulator only — not linked on nRF/XIAO.
 */
#if SLAB_HOST

#include "slab_frames.h"

#include <zlib.h>
#include <string.h>

{chr(10).join(arrays)}

static const struct {{
    const uint8_t *z;
    unsigned zlen;
}} kFrames[SLAB_UI_COUNT] = {{
{chr(10).join(blobs)}
}};

int slab_frame_rgba(slab_ui_t ui, uint8_t *rgba)
{{
    if (!rgba || (unsigned)ui >= SLAB_UI_COUNT) {{
        return -1;
    }}
    uLongf dst = (uLongf)(SLAB_FB_W * SLAB_FB_H * 4);
    if (uncompress(rgba, &dst, kFrames[ui].z, kFrames[ui].zlen) != Z_OK) {{
        return -1;
    }}
    if (dst != (uLongf)(SLAB_FB_W * SLAB_FB_H * 4)) {{
        return -1;
    }}
    return 0;
}}

#endif /* SLAB_HOST */
"""
    OUT.write_text(text)
    print(f"wrote {OUT}")

    bit_arrays = []
    bit_ptrs = []
    for key, filename in FRAMES:
        path = SRC / filename
        im = Image.open(path).convert("RGBA")
        packed = pack_1bit(im)
        if len(packed) != 37 * 128:
            raise SystemExit(f"1-bit size {len(packed)}")
        arr = f"k1{key}"
        bit_arrays.append(c_array(arr, packed))
        bit_ptrs.append(f"    {arr}, /* {filename} */")

    onebit = f"""/* SPDX-License-Identifier: MIT */
/* Instinct 296x128 1-bit panel frames (packed MSB). Regenerated by
 * firmware/tools/bake_instinct_frames.py. No RGBA on target.
 */
#include "slab_frames.h"

#include <string.h>

{chr(10).join(bit_arrays)}

static const uint8_t *const k1bit[SLAB_UI_COUNT] = {{
{chr(10).join(bit_ptrs)}
}};

int slab_frame_1bit(slab_ui_t ui, uint8_t *packed)
{{
    if (!packed || (unsigned)ui >= SLAB_UI_COUNT) {{
        return -1;
    }}
    memcpy(packed, k1bit[ui], SLAB_FB_BYTES);
    return 0;
}}
"""
    OUT_1BIT.write_text(onebit)
    print(f"wrote {OUT_1BIT}")


if __name__ == "__main__":
    main()
