#!/usr/bin/env python3
"""Bake Instinct 296x128 RGBA goldens into zlib blobs for slab_ui_render."""

from __future__ import annotations

import zlib
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "design" / "instinct-firmware-goldens-pr1"
OUT = ROOT / "firmware" / "src" / "slab_frames.c"

FRAMES = [
    ("DEFAULT_HOLE", "01-default-hole.png"),
    ("STROKE_EDIT", "02-stroke-edit.png"),
    ("PUTTS_INPUT", "03-putts-input.png"),
    ("END_HOLE_CONFIRM", "04-end-hole-confirm.png"),
    ("ROUND_COMPLETE_SYNC", "05-round-complete-sync.png"),
    ("DERIVED_STATS", "06-derived-stats.png"),
]


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02X}")
        if len(chunk) == 16:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    blobs = []
    arrays = []
    for key, filename in FRAMES:
        path = SRC / filename
        im = Image.open(path).convert("RGBA")
        if im.size != (296, 128):
            raise SystemExit(f"{path} is {im.size}, expected 296x128")
        z = zlib.compress(im.tobytes(), 9)
        arr = f"kZ{key}"
        arrays.append(c_array(arr, z))
        blobs.append(f"    {{ {arr}, {len(z)} }}, /* {filename} */")

    text = f"""/* SPDX-License-Identifier: MIT */
/* Instinct locked 296x128 RGBA frames (zlib). Regenerated by
 * firmware/tools/bake_instinct_frames.py from
 * design/instinct-firmware-goldens-pr1/. Do not hand-edit.
 */
#include "slab_frames.h"

#include <zlib.h>
#include <string.h>

{chr(10).join(arrays)}

static const struct {{
    const uint8_t *z;
    unsigned zlen;
}} kFrames[SLAB_UI_COUNT] = {{
{chr(10).join(blobs)}
}};

int slab_frame_rgba(slab_ui_t ui, uint8_t *rgba)
{{
    if (!rgba || (unsigned)ui >= SLAB_UI_COUNT) {{
        return -1;
    }}
    uLongf dst = (uLongf)(SLAB_FB_W * SLAB_FB_H * 4);
    if (uncompress(rgba, &dst, kFrames[ui].z, kFrames[ui].zlen) != Z_OK) {{
        return -1;
    }}
    if (dst != (uLongf)(SLAB_FB_W * SLAB_FB_H * 4)) {{
        return -1;
    }}
    return 0;
}}
"""
    OUT.write_text(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
