import { describe, expect, it } from "vitest";
import { computeChecksum, crc32, deriveGir, encodeRound, RoundReceiver, ackFor,
  upsertRound, validateRoundPayload, type RoundPayload, type StoredRound } from "./round-contract";
import untouched from "../../../../protocol/fixtures/untouched.json";
import nine from "../../../../protocol/fixtures/nine-zero-putts.json";
import eighteen from "../../../../protocol/fixtures/eighteen.json";
export function sample(): RoundPayload { return structuredClone(eighteen) as RoundPayload; }
function signed(p: RoundPayload): RoundPayload { p.checksum = computeChecksum(p); return p; }

describe("round v2 C/TypeScript contract", () => {
  it("matches the standard CRC test vector", () => {
    expect(crc32(new TextEncoder().encode("123456789"))).toBe(0xcbf43926);
  });
  it.each([untouched, nine, eighteen])("accepts C-generated bytes and reproduces their checksum", p => {
    expect(validateRoundPayload(p).ok).toBe(true);
    expect(computeChecksum(p as RoundPayload)).toBe(p.checksum);
    expect(JSON.parse(encodeRound(p as RoundPayload))).toEqual(p);
  });
  it("distinguishes missing stats, actual zero putts, and missing par", () => {
    expect(untouched.holes[0].strokes).toBeNull();
    expect(untouched.totals.strokes).toBeNull();
    expect(nine.holes[0].putts).toBe(0);
    expect(deriveGir({ par: 4, strokes: null, putts: null })).toBeNull();
    expect(deriveGir({ par: null, strokes: 1, putts: 0 })).toBeNull();
    expect(deriveGir({ par: 4, strokes: 4, putts: 2 })).toBe(true);
    expect(deriveGir({ par: 4, strokes: 5, putts: 2 })).toBe(false);
  });
  it("validates types, bounds, numbering, totals and checksum independently", () => {
    const mutations: ((p: RoundPayload) => void)[] = [
      p => { p.holes[0].strokes = 1.5; }, p => { p.holes[0].strokes = 0; },
      p => { p.holes[0].putts = -1; }, p => { p.holes[0].putts = 10; },
      p => { p.holes[0].par = 6; }, p => { p.holes[0].hole = 2; },
      p => { p.holes.pop(); }, p => { p.totals.strokes = 999; },
      p => { p.round_sequence = 0; }, p => { p.round_sequence = 0x100000000; },
      p => { p.holes[2].drive_result = "fairway"; }, p => { p.device_id = 'bad"id'; },
    ];
    for (const mutate of mutations) { const p = sample(); mutate(p); expect(validateRoundPayload(signed(p)).ok).toBe(false); }
    expect(validateRoundPayload({ ...sample(), holes_played: "18" }).ok).toBe(false);
    expect(validateRoundPayload({ ...sample(), future: true }).ok).toBe(false);
    expect(validateRoundPayload({ ...sample(), checksum: "crc32:00000000" }).ok).toBe(false);
    expect(validateRoundPayload({ ...sample(), schema_version: 99 })).toMatchObject({ ok: false, preserve: true });
    expect(validateRoundPayload({ ...sample(), holes: [{ hole: 1 }] }).ok).toBe(false);
  });
  it("normalizes key order without depending on sender JSON key order", () => {
    const p = sample(); p.holes[0] = { putts: 2, strokes: 4, drive_result: "fairway", par: 4, hole: 1 };
    expect(validateRoundPayload(p).ok).toBe(true);
  });
  it("does not overwrite app edits or the original payload on a replay", () => {
    const p = sample();
    const stored: StoredRound = { payload: p, queued_at: "2026-09-18T10:00:00Z", import_state: "acknowledged",
      field_provenance: { "holes.1.strokes": "edited_in_app" }, edits: { "holes.1.strokes": 5 } };
    const result = upsertRound([stored], p, "2026-09-19T10:00:00Z");
    expect(result.duplicate).toBe(true);
    expect(result.store[0].payload).toBe(stored.payload);
    expect(result.store[0].edits).toEqual(stored.edits);
    expect(result.store[0].queued_at).toBe(stored.queued_at);
    const conflicting = sample(); conflicting.holes[0].strokes!++; conflicting.totals.strokes!++;
    expect(() => upsertRound([stored], signed(conflicting), "now")).toThrow("round_id conflict");
  });
  it("handles small-MTU chunks, duplicate chunks, gaps and interrupted transfers", () => {
    const p = sample(), bytes = new TextEncoder().encode(encodeRound(p));
    const r = new RoundReceiver(ackFor(p), bytes.length);
    expect(() => r.append(1, bytes.slice(0, 3))).toThrow();
    r.append(0, bytes.slice(0, 17)); r.append(0, bytes.slice(0, 17));
    expect(r.offset).toBe(17);
    expect(() => r.finish()).toThrow("incomplete");
    const changed = bytes.slice(0, 17); changed[0] ^= 1;
    expect(() => r.append(0, changed)).toThrow("conflicting replay");
    for (let offset = 17; offset < bytes.length; offset += 17) r.append(offset, bytes.slice(offset, offset + 17));
    expect(r.finish()).toEqual(p);
    expect(() => new RoundReceiver(ackFor(p), 100000)).toThrow();
    expect(() => r.append(bytes.length, new Uint8Array([0]))).toThrow();
    const wrong = new RoundReceiver({ ...ackFor(p), round_id: "wrong" }, bytes.length);
    wrong.append(0, bytes); expect(() => wrong.finish()).toThrow("identity");
  });
});
